# No Nerd Font overrides (only modules whose defaults use Nerd Font/Powerline glyphs)

[battery]
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[buf]
symbol = "B "

[erlang]
symbol = "â“” "

[fossil_branch]
symbol = "â‡ "

[git_status]
ignore_submodules = true

[git_branch]
symbol = "â‡ "

[hg_branch]
symbol = "â‡ "

[nodejs]
symbol = "[â¬¢](bold green) "

[pijul_channel]
symbol = "ğŸªº "

[pulumi]
symbol = "ğŸ§Š "

[typst]
symbol = "t "
